### ISSUE TITLE
Printing model component with interpolated parameter raises error

### ISSUE THREAD

**Issue by BartOuwehand** [oimodeler/oimodeler#12]
When using an interpolated parameter in a model component (e.g. an infinitesimal ring, uniform disk, etc.), printing the component raises an error (see example code below).

Example code:
import oimodeler as oim
IR = oim.oimIRing(d=oim.oimInterp("wl",wl=[2e-6,2.4e-6],values=[2,6]))
print (IR)

**Comment by MBSck** [comment]
Could you also give a description of the output you get from the error (bascially, the traceback)?

**Comment by AnthonyMeilland** [comment]
Simple fix for now. Print the name of the interpolated parameter class.
Later version should print the __str__ for the interpolated param
