### ISSUE TITLE
`ModuleNotFoundError`: No module named `fastRotator`

### ISSUE THREAD

**Issue by LvHaastere** [oimodeler/oimodeler#20]
```python3
oimodeler/oimodeler/oimCustomComponents/oimFastRotator.py", line 10, in <module>
     from fastRotator import fastRotator
ModuleNotFoundError: No module named 'fastRotator'
```
Currently the installation fails in the __init__.py because of a faulty import.

Can be fixed by moving 
`examples/ExpandingSoftware/fastrotater.py ` 
copy function` fastRotator` into `/oimCustomComponents/oimFastRotator.py`
and change import line
`from fastRotator import fastRotator`

**Comment by AnthonyMeilland** [comment]
Fixed both in the customComponents and example/expandingSoftware directory
