### ISSUE TITLE
fromFT on a model with component with only an _imageFunction fails

### ISSUE THREAD

**Issue by LvHaastere** [oimodeler/oimodeler#21]
Error occured in  `/ExpandingSoftware/createCustomComponentImageSpiral.py`
```python3
> createCustomComponentImageSpiral.py

# Creating a model including the spiral component
 
ud=oim.oimUD(d=1,f=0.2)
c=oimSpiral(dim=256,fwhm=5,P=0.1,width=0.2,pa=30,elong=2,x=10,f=0.8)
m=oim.oimModel(c,ud)
# Plotting images of the model

fig,ax=plt.subplots(1,2,figsize=(10,5))
m.showModel(256,0.1,swapAxes=True,fromFT=False,normPow=1,axe=ax[0],colorbar=False)
m.showModel(256,0.1,swapAxes=True,fromFT=True,normPow=1,axe=ax[1],colorbar=False)
```

`fromFT=True` fails to make the image.
Line 94 `vc=m.getComplexCoherentFlux(spfx,spfy)`
Returns wavelength and a **[nan, ..., nan]** array for coherent flux

![customCompImageSpiralVis](https://user-images.githubusercontent.com/119599212/214870749-91afbc22-33cc-4d49-92c3-09fb5817a796.png)
![customCompImageSpiral](https://user-images.githubusercontent.com/119599212/214870753-b3c56720-4bec-4f61-82eb-9371337d3d2c.png)

**Comment by AnthonyMeilland** [comment]
Very strange, I can't reproduce this error.
It might have something to do with the extrapolation of values outside the image after computing the FFT
I use scipy interpolate.interpn for that with the options bounds_error=False and fill_value=None

Example:
 real=interpolate.interpn(grid,np.real(fft2D),coord,bounds_error=False,fill_value=None)

My version of scipy is 1.9.1 but I think older version (like <1.4) don't have this option.
This would explain the nan everywhere

**Comment by LvHaastere** [comment]
Bug occurred with these versions of packages:

```
>>> pip3 list

(Edited out unimportant ones)

Package              Version     Editable project location
-------------------- ----------- ------------------------------------------------------
astropy              5.1.1
astroquery           0.4.6
emcee                3.1.1
matplotlib           3.5.1
numpy                1.23.4
oimodeler            0.1         /Users/[..]/pro/oimodeler
pandas               1.4.0
pip                  22.2.2
scipy                1.8.0
seaborn              0.11.2
setuptools           49.2.1
tqdm                 4.64.1
```

I updated to **scipy 1.9.1** which fixed the issue!
I suggest we add a section at the `READ.ME` with the needed versions numbers of site-packages.

![customCompImageSpiral](https://user-images.githubusercontent.com/119599212/216046351-a9925105-6b86-4111-b770-545582c0eb24.png)
![customCompImageSpiralVis](https://user-images.githubusercontent.com/119599212/216046378-19038dff-aeae-4f00-9f39-d4bd674e1613.png)
