### ISSUE TITLE
[Bug] Error thrown by not having FFTW installed, stops oimodeler import

### ISSUE THREAD

**Issue by LvHaastere** [oimodeler/oimodeler#60]
**Describe the bug**
When the optional `pyfftw` package is not installed, currently the code throws an import error in `oimFTBackends.py`

**Code and Errorcodes**

> ---> 19 import pyfftw
> ModuleNotFoundError: No module named 'pyfftw'

**Solution**
Solution: Move the import to the try statement at line 25.

> 25 try:
> 26 import pyfftw
> 27  # NOTE: Check if `FFTW` backend is properly installed.

**Comment by MBSck** [comment]
Thanks for the information. The following block: 
```python
try:
    # NOTE: Check if `FFTW` backend is properly installed.
    test_array = pyfftw.empty_aligned(100, dtype="complex128")
    fft_object = pyfftw.FFTW(test_array, test_array, axes=(0,))
    transformed = fft_object(test_array)
    FFTW_CHECK = True
except Exception:
    FFTW_CHECK = False
    def _err() -> None:
        """Import error function that gets called when the FFTWBackend
        dependendy pyfftw has not been properly imported."""
        raise ImportError("This `FFTWBackend`-class has not been defined for "
                          "`oimodeler`. This means that the `FFTW` library is "
                          "either missing or has not been properly "
                          "installed.")
```
was introduced to notice the user if the `FFTW` library has not been properly installed.
However, the dependencies were updated some time after that and theoretically it should work?

As there was also another problem with this recently, I nonetheless I moved it into the try block to make sure it works now and changed the import structure a bit in general.

Could you verify if it work with the newest commit now?

**Comment by MBSck** [comment]
Should be working as of now
