### ISSUE TITLE
`exampleOimFitterEmcee.py` crashes [Bug]

### ISSUE THREAD

**Issue by amerand** [oimodeler/oimodeler#65]
**Describe the bug**
when I run `exampleOimFitterEmcee.py`, I get the error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File [~/Codes/SRC/oimodeler/examples/BasicExamples/exampleOimFitterEmcee.py:47](http://localhost:8888/lab/tree/~/Codes/SRC/oimodeler/examples/BasicExamples/exampleOimFitterEmcee.py#line=46)
     44 fit.prepare(init="random")
     46 # pprinting the initial values of the walkers
---> 47 pprint(f"Initial values of the free parameters for the {fit.nwalkers} walkers")
     48 pprint(fit.initialParams)
     50 # run a 1000 steps fit with fixed starting inital and 1000 steps

AttributeError: 'oimFitterEmcee' object has no attribute 'nwalkers'

**To Reproduce**
run `exampleOimFitterEmcee.py`

**Expected behavior**
not crashing.

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Version: Python=3.12.4, oimodeler=0.8.5, emcee=3.1.6

**Additional context**
if you remove the pprint line, the rest works

**Comment by MBSck** [comment]
Thank you for finding this bug and giving a solution as well.

Works again with commit [c4cdf4e](https://github.com/oimodeler/oimodeler/commit/c4cdf4e2ed6ab8a14f944ca3f8f491cf3a499e74)
